version: '2'

services:
    nats:
        hostname: nats-server
        image: nats-lupinemoon:1.0
        build:
            context: './nats'
        container_name: lupinemoon-nats
        expose:
            - 4222
            - 8222
        ports:
            - 4222:4222
            - 8222:8222
        restart: always

    service-a:
        build:
            context: './service-a'
        depends_on:
            - nats
        restart: always
        ports:
            - 6565:6565
        environment:
            - API_PORT=6565
            - NATS_URL=nats://nats:4222
            - NATS_USER=ruser
            - NATS_PW=T0pS3cr3t

    service-b:
        build:
            context: './service-b'
        depends_on:
            - nats
        restart: always
        environment:
            - NATS_URL=nats://nats:4222
            - NATS_USER=ruser
            - NATS_PW=T0pS3cr3t
            - DADATA_API_KEY=7ded06bb51064631958927b26e115effbfaa9a41
            - DADATA_SECRET_KEY=80852833eacf0fd4be3e04c87e2baf760a4dadb7